# Generated by Django 3.2.15 on 2022-11-29 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('birdsong', '0008_translation_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
