# Generated by Django 3.2.16 on 2023-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0012_auto_20230131_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            model_name='DoubleOptInSettings',
        ),
    ]
